### ISSUE TITLE
checkout geonetwork datadir - destination path '/srv/data/geonetwork' already exists and is not an empty directory

### ISSUE THREAD

**Issue by fvanderbiest** [landryb/georchestra-ansible#6]
```
TASK: [georchestra | checkout geonetwork datadir] ***************************** 
failed: [default] => {"cmd": "/usr/bin/git clone --origin origin --recursive https://github.com/georchestra/geonetwork_minimal_datadir /srv/data/geonetwork", "failed": true, "rc": 128}
stderr: fatal: destination path '/srv/data/geonetwork' already exists and is not an empty directory.

msg: fatal: destination path '/srv/data/geonetwork' already exists and is not an empty directory.

FATAL: all hosts have already failed -- aborting
```

**Comment by landryb** [comment]
If i get it right, at that point tomcat-georchestra was already started, and geonetwork webapp had created its own datadir, not finding it yet - and thus later on git clone fails because the dir was already created by geonetwork itself ? Probably a chicken and egg problem.. wondering if i should only start the different tomcat instances only when every datadir/configfile has been populated/templated.

**Comment by fvanderbiest** [comment]
> wondering if i should only start the different tomcat instances only when every datadir/configfile has been populated/templated

Definitely.

**Comment by landryb** [comment]
Should be fixed by the previous commit (of course untested here)

**Comment by fvanderbiest** [comment]
Works here !
```
PLAY RECAP ******************************************************************** 
default                    : ok=81   changed=23   unreachable=0    failed=0 
```
Thanks.
